name: blog
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
    - beautifulsoup4==4.11.1
    - blinker==1.4
    - commonmark==0.9.1
    - cyclic==1.0.0
    - docutils==0.18.1
    - feedgenerator==2.0.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - importlib-metadata==4.11.4
    - jinja2==3.1.2
    - markdown==3.3.7
    - markupsafe==2.1.1
    - mdx-include==1.4.1
    - pelican==4.7.2
    - pycryptodome==3.14.1
    - pygments==2.12.0
    - pymdown-extensions==9.4
    - python-dateutil==2.8.2
    - pytz==2022.1
    - rcslice==1.1.0
    - rich==12.4.1
    - six==1.16.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - typing-extensions==4.2.0
    - unidecode==1.3.4
    - zipp==3.8.0
