baseURL = "https://hankhjliao.github.io/"
languageCode = 'en-us'
title = 'HJLog'
theme = 'hugo-coder'

paginate = 20
enableEmoji = true

[markup.highlight]
  style = "github-dark"


[params]
  author = "Hung-Ju Liao"
  license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  description = "Hung-Ju Liao's personal website"
  keywords = "blog,personal"
  info = "Software Engineer"
  avatarurl = "images/avatar_512.jpg"
  dateFormat = "January 2, 2006"
  since = 2017

  faviconSVG = "/favicon.ico"
  favicon_32 = "/favicon.ico"
  favicon_16 = "/favicon.ico"

  # Right To Left, shift content direction for languagues such as Arabic
  rtl = false
  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorScheme = "auto"
  # Hide the toggle button, along with the associated vertical divider
  hideColorSchemeToggle = false

  # Series see also post count
  maxSeeAlsoItems = 5

  # Custom CSS
  customCSS = ["css/text.css", "css/toc.css"]
  # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
  customSCSS = []
  # Custom JS
  customJS = []
  # Custom remote JS files
  customRemoteJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[params.giscus] # https://giscus.app
  repo = "hankhjliao/hankhjliao.github.io"
  repoID = "MDEwOlJlcG9zaXRvcnkxMDg0MTEwMjM="
  category = "General"
  categoryID = "DIC_kwDOBnY4j84CdOTa"
  mapping = "title"
  term = ""
  strict = "1"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = ""
  lang = "en"
  loading = "lazy"

[params.umami]
  siteID = "542a7980-0985-44a8-83ba-284fb9366e05"
  scriptURL = "https://analytics.umami.is/script.js"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/hankhjliao/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/hankhjliao/"
[[params.social]]
  name = "Mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  weight = 3
  url = "https://mastodon.social/@hankhjliao"
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 4
  url = "mailto:hankhjliao@gmail.com"
[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 5
  url = "https://hankhjliao.github.io/blog/index.xml"


# Menu links
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "projects/"
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
