name: Pelican Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Pull Codes
      uses: actions/checkout@v2.3.1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the site
      run: |
        make publish

    - name: Add nojekyll
      run: |
        touch ./output/.nojekyll

    - name: Deploy
      run: |
        rm -rf .git
        cd output
        git init
        git config user.name "Hank Liao"
        git config user.email "hankhjliao@gmail.com"
        git remote add origin https://hankhjliao:${{secrets.GH_PAT}}@github.com/hankhjliao/blog.git
        git checkout -b gh-pages
        git add --all
        git commit -m "Deploy"
        git push origin gh-pages --force
